apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
 
namespace: sample-blog

images:
- name: image-registry.openshift-image-registry.svc:5000/sample-blog/django 
  newName: image-registry.openshift-image-registry.svc:5000/sample-blog/django
  newTag: v0.1
- name: image-registry.openshift-image-registry.svc:5000/sample-blog/nginx
  newName: image-registry.openshift-image-registry.svc:5000/sample-blog/nginx
  newTag: v0.1

resources:
- django-configmap.yaml
- django-deployment.yaml
- django-secret.yaml
- django-service.yaml
- mysql-configmap.yaml
- mysql-secret.yaml
- mysql-service.yaml
- mysql-statefulset.yaml
- nginx-deployment.yaml
- nginx-route.yaml
- nginx-service.yaml
- redis-configmap.yaml
- redis-service.yaml
- redis-statefulset.yaml
- sample-blog-sa.yaml
- network-policy.yaml
